[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dep-wofs"
version = "0.2.0"
description = "Water observations mapping for Digital Earth Pacific"
authors = [{"name" = "Jesse Anderson <jesse.anderson@gmail.com>"}]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["dependencies"]

[tool.setuptools]
packages = [ "dep_wofs" ]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
