apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: wofl-sns-sensor
  namespace: argo
spec:
  template:
    serviceAccountName: test-landsat-sa
  eventBusName: test-eb
  dependencies:
    - name: test-dependency
      eventSourceName: test-sns-es
      eventName: example
  triggers:
    - template:
        name: sns-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: aws-sns-workflow-
              spec:
                entrypoint: main
                podGC:
                  strategy: OnWorkflowSuccess
                ttlStrategy:
                  secondsAfterSuccess: 60
                arguments:
                  parameters:
                  - name: message
                templates:
                - name: main
                  dag:
                    tasks:
                    - name: extract-message
                      template: extract-sns-message
                      arguments:
                        parameters:
                          - name: sns-message
                            value: "{{workflow.parameters.message}}"
                    - name: process-wofl
                      dependencies: [extract-message]
                      template: process-wofl
                      arguments:
                        parameters:
                        - name: message
                          value: "{{tasks.extract-message.outputs.result}}"
                - name: extract-sns-message
                  inputs:
                    parameters:
                    - name: sns-message
                  script:
                    image: node:12-alpine
                    command: [node]
                    source: |
                      const snsMessage = {{inputs.parameters.sns-message}};
                      console.log(snsMessage.Message);
                - name: process-wofl
                  inputs:
                    parameters:
                    - name: message
                  container:
                    image: "ghcr.io/digitalearthpacific/dep-wofs:sns-test-1"
                    command: [python]
                    args: 
                      - dep_wofs/process_sns_message.py
                      - "{{ inputs.parameters.message }}"
          parameters:
            - src:
                dependencyName: test-dependency
                dataKey: body
              dest: spec.arguments.parameters.0.value
